# the required packages can be installed with
# conda env create -n bds_visualization --file=conda_requirements.yaml
# conda activate bds_visualization

channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.12
  - pip
  - pip:
    - dash==2.0.0
    - dash-bootstrap-components==1.0.2
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - flask==2.0.2
    - numpy==1.22.1
    - pandas==1.3.4
    - plotly==5.4.0
    - werkzeug==2.0.2
    - geojson==3.0.1
